white-listing parameters
Dynom/proxima pull request #1
Opened 2017-04-24 16:03 UTC by Dynom

Only allow a predefined set of parameters in the URL, e.g.:

```
./proxima -allowed-params=width,height,url
```

With:
```
?width=100&height=100&file=/path/to/image.jpg
```

would result in:
```
error="parameter is not white-listed" parameter=url allowed=width,height,url
```

2017-04-25 08:26 UTC, yazgazan requested changes

2017-04-25 08:26 UTC, yazgazan commented on handlers/allowedparams.go
> +					http.Error(w, "Unregisterd parameter", http.StatusNotAcceptable)
See comment on #2 

(https://github.com/Dynom/proxima/pull/2/files/b7ea268c1adb92eb875207a99bcc9939ac1661b9#r113132120)

2017-04-25 08:26 UTC, yazgazan commented on main.go
> +	allowedImaginaryParams string
See comment on #2 

(https://github.com/Dynom/proxima/pull/2/files/b7ea268c1adb92eb875207a99bcc9939ac1661b9#r113132557)

2017-04-26 09:05 UTC, yazgazan requested changes

2017-04-26 09:05 UTC, yazgazan commented on main.go
> +	flag.Var(&allowedHosts, "allow-host", "Repeatable flag (or a comma-separated list) for hosts to allow for the URL parameter (e.g. \"d2dktr6aauwgqs.cloudfront.net\")")
Should be renamed `allow-hosts` (with an ending `s`)

2017-04-26 09:05 UTC, yazgazan commented on argumentlist.go
> +	return nil
Would returning an error when `value` is empty make sense ? (an empty string would be added to the `argumentList`)

2017-04-26 09:42 UTC, Dynom commented on argumentlist.go
> +	return nil
It's not a problem for the implementation, empty values are just ignored during processing. So I wouldn't consider it an error.

2017-04-26 10:17 UTC, yazgazan approved these changes

2017-04-26 10:21 UTC, merged