White list actions
Dynom/proxima pull request #2
Opened 2017-04-24 16:08 UTC by Dynom

Only allow a predefined set of actions, e.g.:

```
./proxima -allowed-actions=crop,resize
```

With:
```
/enlarge?width=100&height=100&file=/path/to/image.jpg
```

would result in:
```
error="action is not white-listed" action=enlarge allowed=crop,resize
```

2017-04-25 08:23 UTC, yazgazan requested changes

2017-04-25 08:23 UTC, yazgazan commented on handlers/allowedactions.go
> +				http.Error(w, "Unregisterd action", http.StatusNotAcceptable)
This should be a `http.StatusBadRequest` or `http. StatusForbidden StatusForbidden`. 406 Not Acceptable is only appropriate if the client's accept header doesn't match anything the server can generate/output.

2017-04-25 08:23 UTC, yazgazan commented on handlers/allowedparams.go
> +					http.Error(w, "Unregisterd parameter", http.StatusNotAcceptable)
Dito

2017-04-25 08:23 UTC, yazgazan commented on main.go
> +	allowedImaginaryActions string
Shouldn't `allowedImaginaryParams` and `allowedImaginaryActions` be `argumentList`s ?
Or maybe another list type that accepts comma-separated values and decode them into a `[]string` ?

2017-04-26 08:30 UTC, Dynom commented on main.go
> +	allowedImaginaryActions string
I was a bit in doubt about the `argumentList` thing. Repeated arguments made sense for domains, but I don't like it for parameters or actions. But I like a different type that generalises comma-separated values. :+1:

2017-04-26 10:17 UTC, yazgazan approved these changes

2017-04-26 10:21 UTC, merged